"""fix backpopulate name error

Revision ID: 2ffd03dcea4e
Revises: cfac9328bfa3
Create Date: 2025-04-11 13:05:29.346738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffd03dcea4e'
down_revision: Union[str, None] = 'cfac9328bfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
